### ISSUE TITLE
Plugin breaks against webpack magic comments

### ISSUE THREAD

**Issue by ematipico** [airbnb/babel-plugin-dynamic-import-node#36]
Webpack introduced recently a non-standard feature to customize the `import()` function

https://webpack.js.org/api/module-methods/#import-

Unfortunately using these comments breaks the plugin and the `import()` doesn't get transpilled correctly.

*.babelrc*
```json
{ "plugins": ["dynamic-import-node"] }
```
*index.js, broken syntax*
```js
import(/* webpackChunkName: "Foo.Module" */ './foo.js');
```

*index.js, correct syntax*
```js
import('./foo.js');
```

**Comment by ljharb** [comment]
Given that it's non-standard, I'd say it's *supposed* to break.

**Comment by lencioni** [comment]
@ljharb can you explain a bit more. Isn't this just a comment? Why would a comment break something?

**Comment by ematipico** [comment]
Per se the comment is harmless, it's just a comment. webpack uses those comments to do some magic under the hoods. I just said "non-standard" because I don't know if the standard `import()` would break, but considering it's just a comment, it shouldn't.

**Comment by ljharb** [comment]
I believe the spec grammatically requires the keyword import, an open paren, and then a value - if it allows for this comment, then it should definitely work in this transform - but I was under the impression that the spec intentionally restricted what productions could be used.

However, since you can use any variable there, the comment might actually be valid. If we can verify what the proposal spec actually allows, we can probably move forward here.

**Comment by vlad-zhukov** [comment]
I use webpack comments and this plugin together, and haven't had any problems. Perhaps that's because I do it like this for a better readability: `import('./foo.js' /* webpackChunkName: "Foo.Module" */)`.
@ematipico can you try this?

**Comment by ljharb** [comment]
@ematipico I'd be interested in reviewing a PR that allows for this, while we figure out if it's valid syntax or not separately.
